@startuml
class RpnCalculator
RpnCalculator : Stack stack

RpnApplication ..> RpnCalculatorFactory : create()
RpnCalculatorFactory -> RpnCalculator : creates
RpnCalculatorFactory -> Operation: creates
RpnApplication *- RpnCalculator

interface Command
Command : apply(Stack stack)
Command : undo(Stack stack)
Command <|.down. DoOperationCommand
Command <|.down. PushNumberCommand

interface Operation
Operation : operate(Stack stack, Stack numbersPoped)
Operation <|.down. BinaryOperation
Operation <|.down. UnaryOperation
Operation <|.down. ClearOperation

DoOperationCommand o-down- Operation
RpnCalculator *- "*" Operation
RpnCalculator *- "*" Command
@enduml